// <auto-generated />
namespace TinyCQRS.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SimplifyEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SimplifyEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "201302082318476_SimplifyEvents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
