// <auto-generated />
namespace TinyCQRS.ReadModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CrawlCounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrawlCounts));
        
        string IMigrationMetadata.Id
        {
            get { return "201302090212268_CrawlCounts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
