// <auto-generated />
namespace TinyCQRS.ReadModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CrawlCompletionTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrawlCompletionTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201302072229114_CrawlCompletionTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
